version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/CyberChan"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"