version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/CyberChan"
    schedule:
      interval: "weekly"
    target-branch: "test"
    groups:
      # Specify a name for the group, which will be used in pull request titles
      # and branch names
      nuget:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
    ignore:
      - dependency-name: "DSharpPlus"
      - dependency-name: "DSharpPlus.Commands"
      - dependency-name: "DSharpPlus.Interactivity"
      - dependency-name: "DSharpPlus.VoiceNext"
      - dependency-name: "Betalgo.Ranul.OpenAI"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
