#  Template .NET Core build

#  This template allows you to validate your .NET Core package.
#  The workflow allows running tests and code linting on the default branch.

image: mcr.microsoft.com/dotnet/sdk:8.0

definitions: 
  steps:
    - step: &build-test
        name: Build and Test
        caches:
          - dotnetcore
        script:
          - dotnet clean -o Build
          - dotnet restore
          - dotnet build --no-restore --configuration Release -o Build
        artifacts:
          - Build/**
    - step: &deploy
        name: Deploy to test
        deployment: Test
        # trigger: manual  # Uncomment to make this a manual deployment.
        script:
          - echo "Deploying code" 
          - pipe: atlassian/rsync-deploy:0.4.4
            variables:
              USER: $user
              SERVER: $server
              REMOTE_PATH: $directory
              LOCAL_PATH: 'Build/'
              DELETE_FLAG: 'false'
          - pipe: atlassian/ssh-run:0.3.0
            variables:
              SSH_USER: $user
              SERVER: $server
              COMMAND: $command
          
pipelines:
  branches:
     test:
       - step: *build-test
       - step: *deploy
          
     master:
       - step: *build-test
       - step: 
          <<: *deploy
          name: Deploy to Prod
          deployment: Production
