#  Template .NET Core build

#  This template allows you to validate your .NET Core package.
#  The workflow allows running tests and code linting on the default branch.

image: mcr.microsoft.com/dotnet/core/sdk:3.1

pipelines:
  default:
    - step:
        name: Build and Test
        caches:
          - dotnetcore
        script:
          - dotnet restore
          - dotnet build --no-restore --configuration Release -o Build
        artifacts:
          - Build/**
  branches:
     test:
       - step:
          name: Deploy to test
          deployment: Test
          # trigger: manual  # Uncomment to make this a manual deployment.
          script:
            - echo "Deploying to test environment" 
            - pipe: atlassian/scp-deploy:1.0.0
              variables:
                USER: $user
                SERVER: $server
                REMOTE_PATH: $directory
                LOCAL_PATH: Build/*
     master:
       - step:
          name: Deploy to prod
          deployment: Production
          # trigger: manual  # Uncomment to make this a manual deployment.
          script:
            - echo "Deploying to production environment" 
            - pipe: atlassian/scp-deploy:1.0.0
              variables:
                USER: $user
                SERVER: $server
                REMOTE_PATH: $directory
                LOCAL_PATH: Build/*
