name: Code Quality

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Check code formatting
      id: format
      run: dotnet format --verify-no-changes --verbosity diagnostic
      continue-on-error: true

    - name: Warn about code formatting issues
      if: steps.format.outcome == 'failure'
      run: echo "::warning::Code formatting issues found. Please run 'dotnet format' to fix them."
