name: Deploy

on:
  push:
    branches: [ test, master ]
  workflow_dispatch:  # Allow manual deployment

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release -o Build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: deployment-build
        path: Build/

  deploy-test:
    if: github.ref == 'refs/heads/test'
    needs: build
    runs-on: ubuntu-latest
    environment: Test
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: deployment-build
        path: Build/
        
    - name: Deploy to test environment
      run: |
        echo "Deploying to test environment"
        # Add deployment steps here using secrets for server credentials
        # Example using SSH:
        # - name: Deploy via SSH
        #   uses: appleboy/ssh-action@v1.0.3
        #   with:
        #     host: ${{ secrets.TEST_SERVER }}
        #     username: ${{ secrets.TEST_USER }}
        #     key: ${{ secrets.SSH_PRIVATE_KEY }}
        #     source: "Build/"
        #     target: ${{ secrets.TEST_DIRECTORY }}

  deploy-production:
    if: github.ref == 'refs/heads/master'
    needs: build
    runs-on: ubuntu-latest
    environment: Production
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: deployment-build
        path: Build/
        
    - name: Deploy to production environment
      run: |
        echo "Deploying to production environment"
        # Add deployment steps here using secrets for server credentials